---
title: "MT Cars Ultra Flex"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: "cerulean"
runtime: shiny
---

<style type="text/css">

body{ /* Normal  */
   font-size: 10px;
}
</style>

```{r setup, include = FALSE}


library(flexdashboard)
library(dplyr)

## want to allow filtering on any column

fields <- colnames(mtcars)


## filter functions

filter1_by <- function(df, f1, fv1) {
  filter_f1 <- quo(f1)

  df %>%
   dplyr::filter_at(vars(!!filter_f1), all_vars(. == fv1))
}


filter2_by <- function(df, f1, fv1, f2, fv2) {
  filter_f1 <- quo(f1)
  filter_f2 <- quo(f2)

  df %>%
   dplyr::filter_at(vars(!!filter_f1), all_vars(. == fv1)) %>%
    dplyr::filter_at(vars(!!filter_f2), all_vars(. == fv2))
}

filter3_by <- function(df, f1, fv1, f2, fv2, f3, fv3) {
  filter_f1 <- quo(f1)
  filter_f2 <- quo(f2)
  filter_f3 <- quo(f3)

  df %>%
   dplyr::filter_at(vars(!!filter_f1), all_vars(. == fv1)) %>%
    dplyr::filter_at(vars(!!filter_f2), all_vars(. == fv2)) %>%
    dplyr::filter_at(vars(!!filter_f3), all_vars(. == fv3))

}




knitr::opts_chunk$set(echo = FALSE)
```

Sidebar {.sidebar}
=========================================


Select your filter fields and values.

``` {r input, echo = FALSE}

mainPanel(
 selectInput("filter1", "Select filter criteria 1:", choices = fields),
 uiOutput("filter1choice"),
 checkboxInput("filter2req", "Add second filter?"),
 conditionalPanel(condition = 'input.filter2req', 
                  uiOutput("filter2eval"),
                  uiOutput("filter2choice"),
                  checkboxInput("filter3req", "Add third filter?")),
 conditionalPanel(condition = 'input.filter3req & input.filter2req', 
                  uiOutput("filter3eval"),
                  uiOutput("filter3choice")),
 width = "350px"
)


choicevec1 <- reactive({
    mtcars %>%  dplyr::select(input$filter1) %>% unique() %>% dplyr::arrange_(input$filter1)
}) 

output$filter1choice <- renderUI(
  selectInput("filter1val", "Select filter 1 condition:", choices = choicevec1())
)

output$filter2eval <- renderUI({
  selectInput("filter2", "Select filter criteria 2:", choices = sort(fields[fields != input$filter1]))
})

choicevec2 <- reactive({
    filter1_by(mtcars, input$filter1, input$filter1val) %>% select(input$filter2) %>% unique() %>% dplyr::arrange_(input$filter2)
}) 

output$filter2choice <- renderUI(
  selectInput("filter2val", "Select filter 2 condition:", choices = choicevec2())
)

output$filter3eval <- renderUI({
  selectInput("filter3", "Select filter criteria 3:", choices = sort(fields[!fields %in% c(input$filter1, input$filter2)]))
})

choicevec3 <- reactive({
    filter2_by(mtcars, input$filter1, input$filter1val, input$filter2, input$filter2val) %>% select(input$filter3) %>% unique() %>% dplyr::arrange_(input$filter3)
}) 

output$filter3choice <- renderUI(
  selectInput("filter3val", "Select filter 3 condition:", choices = choicevec3())
)



```


Filtered Results
=============================================

Column 
------------------------------------------------------


```{r}

kable1 <- reactive({
  
  if (input$filter3req & input$filter2req) {
    filter3_by(mtcars, input$filter1, input$filter1val, input$filter2, input$filter2val, input$filter3, input$filter3val)
      } else if (input$filter2req) {
    filter2_by(mtcars, input$filter1, input$filter1val, input$filter2, input$filter2val)
      } else {
    filter1_by(mtcars, input$filter1, input$filter1val)
      }
  
})

renderTable(kable1())


```
